### ISSUE TITLE
Fetching tag data for a review item also gathers the duplicate's tags

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR.Net#2]
The chat bot got to [this](http://stackoverflow.com/review/close/7179837) review and crashed because there were duplicate PHP tags.

![image](https://cloud.githubusercontent.com/assets/8290105/6424172/625df99e-bec1-11e4-9c34-6beb62063c24.png)

The first 4 are the tags for the post, and the last 3 are for the duplicate. I don't want the duplicate's tags.

Line 116 of ReviewItem looks like this

```
foreach (var tag in dom[".post-taglist a"])
```

You should be able to change this to

```
foreach (var tag in dom[".js-tab-question .post-taglist a"])
```

It seems `.js-tab-question` is wrapped around the post you want, and `.js-tab-dup-<#>` for any duplicates.

**Comment by ArcticEcho** [comment]
Good catch, I'll roll out a fix today.
