### ISSUE TITLE
Restructure all teh tings

### ISSUE THREAD

**Issue by ArcticEcho** [SO-Close-Vote-Reviewers/SOCVR.Net#4]
The current monitoring mechanism works™, but it's just too fragmented for my liking. So, I'm going to completely overhaul the current design with something cleaner, and easier to maintain.

(This may also be a candidate for a stable release.)

**Comment by K-Guan** [comment]
So you're about to create  a new branch, which:

> Completely overhaul the current design with something cleaner, and easier to maintain.

Sounds good, when can you finish this?

**Comment by ArcticEcho** [comment]
Well, as any dev knows, putting an accurate completion date to a project is difficult. But if I had to make an estimation, perhaps, six to eight weeks.

Just kidding, seriously though, I'm hoping to get this done in under two/three weeks.

**Comment by ArcticEcho** [comment]
(Kinda forgot about this issue, it was resolved around 16 Dec 2015.)
